# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

# Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
    global:
        - CRATE_NAME=cec-rs

matrix:
    # These are all the build jobs. Adjust as necessary. Comment out what you
    # don't need
    include:
        # Linux
        - env: TARGET=aarch64-unknown-linux-gnu
        - env: TARGET=arm-unknown-linux-gnueabi
        - env: TARGET=armv7-unknown-linux-gnueabihf
        - env: TARGET=i686-unknown-linux-gnu
        #- env: TARGET=i686-unknown-linux-musl
        - env: TARGET=mips-unknown-linux-gnu
        - env: TARGET=mips64-unknown-linux-gnuabi64
        - env: TARGET=mips64el-unknown-linux-gnuabi64
        - env: TARGET=mipsel-unknown-linux-gnu
        - env: TARGET=x86_64-unknown-linux-gnu
        #- env: TARGET=x86_64-unknown-linux-musl
        # Windows
        #- env: TARGET=x86_64-pc-windows-gnu

before_install:
    - set -e
    - rustup self update

install:
    - sh ci/install.sh
    - source ~/.cargo/env || true

script:
    - bash ci/script.sh

after_script: set +e

before_deploy:
    - sh ci/before_deploy.sh

deploy:
    # update `api_key.secure`
    # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
    # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
    # - Paste the output down here
    api_key:
        secure: DeyAgMrywNAuTD8E97lVnu1Kdv08wckQoE6/lMDuW6R3CIz3RhlqwMUS01MjM0gAfcTpIeK1FIe007IFLSAZPBuneDx+qmAGssNGqhI87oA2m/UZ+dCpAPBnCxJAUYW+SagBBsSYMGF0CPhQPI+hIF7xE6vCKSheLy9SzasgZI3aklFzkFWgDmbFEfzvooxWnAncFT+M952Zgqw7Fu5z0wSVw5TEC371wDYVzzQQNEd0eSjQkl6T9SC5EbiHa9toArzemJVGQ2CRi/OKKOLTsp4d16YEN50T7u6T2U3VM14RrxJZnVPPmfx/C/WxCn5ROa1UBWlPzdrmQGYnVHUUNp5eRL2zJAJkcnn/acSBkHEdoKnlLLVUhZsac/znK/sG/6s8kKsgAsjolIIQigvO2QaQ0zR6vNdDz8XXzL8zE6M4E1/v/hbBDEGnFJTy6dDujX4PQH7dBCexR/HzUJ8fKdLny5X4Q64w/4eWWZp/CyCdZcuYXM/DCsWYJVh81U2IHdigoIM89MkAdl54f2HWVcNjU7ReZb/+l8D+pap1fk2BYi0SEEzWow+cuVzf/B/55HNlF0nFNd9G3J8j1POgpUeTqI+ymRllmi7pDPNJkFd6vQdSaQ1E2n/Ae1UuFtttnjzccRK5rdubOEae+qDAVDJeToMv4RQ72+ZSYMU/IYI=
    file_glob: true
    file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
    on:
        # This is a library, do not deploy
        condition: $DEPLOY = never
        tags: true
    provider: releases
    skip_cleanup: true

cache: cargo
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

branches:
    only:
        # release tags
        - /^v\d+\.\d+\.\d+.*$/
        - master

notifications:
    email:
        on_success: never
