[package]
name = "cec-rs"
version = "0.1.0"
authors = ["salski"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcec-sys = { path = "../libcec-sys" }
num-traits = "0.2"
num-derive = "0.2.5"
arrayvec = "0.5.0"