[package]
name = "cec-rs"
version = "0.1.0"
authors = ["salski"]
edition = "2018"
license = "GPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.3.0"
arrayvec = "0.5.1"

[dependencies.libcec-sys]
version = "0.1.0"
path = "../libcec-sys"